// Code generated by github.com/fjl/gencodec. DO NOT EDIT.

package types

import (
	"encoding/json"
	"errors"

	"github.com/scroll-tech/go-ethereum/common/hexutil"
)

var _ = (*rowConsumptionMarshaling)(nil)

// MarshalJSON marshals as JSON.
func (r RowConsumption) MarshalJSON() ([]byte, error) {
	type RowConsumption struct {
		Rows hexutil.Uint64 `json:"rowConsumption" gencodec:"required"`
	}
	var enc RowConsumption
	enc.Rows = hexutil.Uint64(r.Rows)
	return json.Marshal(&enc)
}

// UnmarshalJSON unmarshals from JSON.
func (r *RowConsumption) UnmarshalJSON(input []byte) error {
	type RowConsumption struct {
		Rows *hexutil.Uint64 `json:"rowConsumption" gencodec:"required"`
	}
	var dec RowConsumption
	if err := json.Unmarshal(input, &dec); err != nil {
		return err
	}
	if dec.Rows == nil {
		return errors.New("missing required field 'rowConsumption' for RowConsumption")
	}
	r.Rows = uint64(*dec.Rows)
	return nil
}
